name: Build & Deploy to Mittwald

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy via lftp
        run: |
          sudo apt-get install -y lftp
          lftp -u "${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }}" sftp://${{ secrets.FTP_SERVER }} <<EOF
          set sftp:auto-confirm yes
          set net:max-retries 3
          set mirror:parallel-transfer-count 5
          mkdir -p /cx-platform
          mkdir -p /workspace
          rm -f /storybook/index.html
          mirror --reverse --only-newer --parallel=5 --verbose ./storybook-static /storybook
          put ./storybook-static/index.html -o /storybook/index.html
          put public/index.html -o /cx-platform/index.html
          mirror --reverse --only-newer --verbose ./public/workspace /workspace
          bye
          EOF
